# Site settings
title: Iran University of Science and Technology
course_name: ريزپردازنده و زبان اسمبلي
course_description: Assembly
course_semester: "Fall 2019"
description: |
    Instructor: Amir Mahdi Hosseini

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/course_template" # the subpath of your site, e.g. /blog/
url: "http://sauleh.github.io/course_template" # the base hostname & protocol for your site
syllabus: http://sauleh.github.io/course_template/syllabus/
githubdir: 

# Author/user information
email: instructor-first-name@iust.ac.ir
twitter_username: broken_twitter 
github_username:  broken_github
authorurl: "http://borken-url.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements: اين درس دانش پايهاي ريزپردازنده و ميکروکنترلر را براي دانشجويان فراهم ميآورد، به گونهاي که آنها را قادر￼￼ به طراحي سيستمهاي مبتني بر ريزپردازنده و ميکروکنترلر خواهد ساخت. بخش قابل توجهي از اين درس بر ريزپردازنده 8186/88 بنا نهاده شده است. يادگيري اين ريزپردازنده، در عين سادگي ساختار نسبت به پردازندههاي بسيار پيشرفتهتر امروزي، اطلاعات پايهاي مهمي از مفاهيم طراحي ريزپردازنده را به دانشجويان
منتقل ميکند و آنها را براي يادگيري ساختارهاي پيچيدهتر آماده ميسازد. در عين حال در اين درس مباح مختصري از ريزپردازنده پيشرفتهتر پنتيوم مانند ثباتها، روشهاي آدرسدهي و مفاهيم عمليات حالت حقيقي و حفاظتشده براي نشان دادن مختصري از تفاوتهاي آن با ريزپردازنده 8186 (اختياري)، معرفي خواهد شد. بخشي ديگري از اين درس به معرفي ميکروکنترلرهاي خانواده AVR اختصاص يافته است تا بدين ترتيب دانشجويان با امکانات تعبيه شده در ميکروکنترلرها و مفاهيم مطرح در سيستمهاي نهفته شامل اجتماع انواع حافظهها، درگاههاي موازي قابل برنامهريزي، انواع وقفههاي سختافزاري و نرمافزاري و اولويت دهي آنها، زمانسنج/شمارنده براي استفاده در شمارش وقايع، زمانگيري و توليد سيگنالهاي از نوع PWM، مقايسهکننده آنالوگ، مبدل آنالوگ به ديجيتال و بعضي از انواع پروتکلهاي ارتباط سريال آشنا شوند. به منظور آشنايي با زبان اسمبلي، در اين درس ضمن آشنايي با مفاهيم اصلي زبان اسمبلي، دستورات اسمبلي ريزپردازنده 8186 و خانواده AVR مطرح گرديده و اسمبلرها و محيطهاي توسعه مجتمع )IDE( براي آنها
معرفي خواهند شد.
        output: true

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
