# Site settings
title: Iran University of Science and Technology
course_name: ريزپردازنده و زبان اسمبلي
course_description: Assembly
course_semester: "Fall 2019"
description: |
    Instructor: Amir Mahdi Hosseini

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/course_template" # the subpath of your site, e.g. /blog/
url: "http://sauleh.github.io/course_template" # the base hostname & protocol for your site
syllabus:
تراشههاي ريزپردازنده (اختياري) 
2- مفاهيم پايه در سيستمهاي رايانهاي شامل: نمودار بلوکي يک ريزپردازنده و معرفي اجمالي اجزاء آن، واکشي و اجراي دستور، خطوط گذرگاه سهگانه (گذرگاه آدرس، داده و کنترل)، واحد پردازشگر مرکزي، حافظه و I/O، دستورالعملها، کدهاي عملياتي و عملوند و معرفي انواع چرخههاي گذرگاه
(bus cycles)
3- ساختار واحد پردازشگر مرکزي ريزپردازنده 8186/8188: ساختار واحد پردازشگر مرکزي 8186/88، واکشي و اجراي دستورالعمل، معرفي ثباتها، حافظه قسمتبندي شده، آدرسهاي فيزيکي و منطقي
4- معرفي اجمالي روشهاي آدرسدهي و دستورالعملهاي 8186/8188 9- آشنايي اجمالي با اجزاء و قابليتهاي ريزپردازنده پنتيوم، عمليات حالت حقيقي و حفاظت شده،
روشهاي آدرسدهي در پنتيوم (اختياري) 6- آشنايي با برنامهنويسي به زبان اسمبلي: معرفي شبهکدها، آموزش نصب و کار در محيط اسمبلر
NASM و نوشتن چند برنامه اسمبلي به زبان ريزپردازنده 8186/8188 7- طراحي واحد پردازشگر مرکزي 8186/8188 شامل: ساختار سيستمهاي سهگذرگاهه، زمانبندي
انواع سيکلهاي گذرگاه، معرفي پايههاي 8186/8188 در حالت کمينه، طراحي سختافزار پايه مبتني بر ريزپردازنده 8186/8188 شامل معرفي و توليد سيگنالهاي بازنشاني، پالس ساعت و Ready
8- حافظه در سيستمهاي مبتني بر ريزپردازنده: تعريف حافظه و مفاهيم پايهاي آن، طبقهبندي حافظهها، حافظه با دسترسي ترتيبي و تصادفي، حافظههاي ايستا، حافظههاي پويا، حافظههاي فقط خواندني، حافظههاي EPROM و EEPROM، حافظههاي خواندني-نوشتني، حافظه فللَش (اختياري)، تعيين پارامترهاي زمانبندي خواندن/نوشتن در حافظه درحالت کمينه ريزپردازنده
8186/8188، تهيه نقشه حافظه، چگونگي ارتباط SRAM و ROM با ريزپردازنده 8186/8188 و تکنيکهاي رمزگشايي کامل و جزئي آدرس براي دسترسي به حافظهها
1- روشهاي پايه ورودي/خروجي )I/O(: زمانبندي ارتباط ريزپردازنده با درگاههاي ورودي/خروجي I/O، طراحي درگاه ورودي و خروجي موازي، I/O نگاشته شده در حافظه، I/O برنامهريزي شده و روش سرکشي، I/O وقفهگرا، انواع وقفه، زمانبندي وقفه خارجي، اولويتدهي وقفهها، زمان
پاسخگويي به وقفه، بردار وقفه و روال سرويسدهي وقفه، معرفي اجمالي دسترسي مستقيم به حافظه (DMA) (اختياري)، طراحي کيبورد سطري و ماتريسي، طراحي مدار اتصال نمايش دهندههاي 7 قطعهاي، رله و LED به يک سيستم مبتني بر ريزپردازنده، معرفي اجمالي ارتباط
فهرست مباح￼￼￼
58￼
سريال همگام و ناهمگام.￼￼
01- معرفي اجمالي ميکروکنترلرها (مثل ميکروکنترلر ATMega16 از خانواده AVR يا يک
ميکروکنترلر از خانواده ARM يا هر ميکروکنترلر مناسب ديگر) شامل معرفي معماري و هسته مرکزي ميکروکنترلر شامل: معرفي پايهها، انواع منابع بازنشاني، انواع منابع ساعت، واکشي و اجراي دستورالعملها، حالتهاي آدرسدهي و معرفي اجمالي دستورالعملها، فضاي حافظه و انواع حافظه
داخلي، مجموعه ثباتها، ثبات وضعيت، تغذيه ميکروکنترلر، معرفي بيتهاي فيوز. 00- آشنايي با واحدهايهاي داخلي ميکروکنترلر: آشنايي با حالتهاي صرفهجويي در مصرف توان، وقفههاي داخلي و خارجي، زمانسنج/شمارنده، زمانسنج نگهبان، مقايسه کننده آنالوگ، مبدل آنالوگ به ديجيتال، معرفي اجمالي واسط ارتباط سريال USART، معرفي اجمالي واسطهاي سريال
SPI (اختياري) و TWI (اختياري)
02- معرفي اجمالي يک محيط IDE براي توسعه برنامه براي ميکروکنترلر و نوشتن برنامه به زبان
اسمبلي و يک زبان سطح بالا (مثل: Atmel Studio و CodeVision) (معرفي توسط استاد يا مطالعه توسط دانشجويان)
03- نکات مهم در طراحي سختافزار مدارات مبتني بر ريزپردازنده (اختياري) شامل مباح نويز و تاثير آن بر سيستمهاي ديجيتال، رعايت سطوح ولتاژ و جريان در اتصال قطعات از خانواده و تکنولوژيهاي مختلف، اثر انعکاس، اثر ظرفيت خازني در ورودي پايههاي تراشهها، تاخير انتشار،
دلايل استفاده از بافر و مانند آن (اختياري)
githubdir: 

# Author/user information
email: instructor-first-name@iust.ac.ir
twitter_username: broken_twitter 
github_username:  broken_github
authorurl: "http://borken-url.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
