# Site settings
title: Iran University of Science and Technology
course_name: ريزپردازنده و زبان اسمبلي
course_description: This course provides students with the basic knowledge of microprocessor and microcontroller in a way that will enable them to design microprocessor and microcontroller based systems A significant part of this lesson is based on the 818688 microprocessor Learning this microprocessor while simplifying the structure of todays more advanced CPUs provides students with basic information about microprocessor design concepts Transmits and prepares them for learning more complex structures In this lesson however we will briefly discuss some of the more advanced Pentium microprocessors such as registers addressing methods and concepts of true and protected mode operation to briefly outline their differences with the 8186 optional microprocessor Another part of the course is dedicated to introducing the AVR family microcontrollers to provide students with microcontroller enabled features and concepts embedded in systems including assembly of memory types programmable parallel ports types of hardware interrupts and hardware and software Counter Learn about event counting timing and output of PWM signals analog comparators analog to digital converters and some types of serial communication protocols In order to become familiar with assembly language this lesson introduces the basic concepts of assembly language 8186 microprocessor assembly and AVR family and assemblies and development environments IDEs for them Will be introduced
course_semester: "Jan 2020"
description: |
    Instructor: Amir Mahdi Hosseini

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/course_template" # the subpath of your site, e.g. /blog/
url: "http://sauleh.github.io/course_template" # the base hostname & protocol for your site
syllabus: http://sauleh.github.io/course_template/syllabus/
githubdir: 

# Author/user information
email: monazzah@iust.ac.ir
twitter_username: broken_twitter
github_username:  broken_github
authorurl: "http://borken-url.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:<li class="no-p-margin">
        
            
                New Assignment released: [<a href="/co98/assignments/03_assignment">انتخاب استاد و درس برای طراحی وب</a>]
            
        
    </li>
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
