# Site settings
title: Iran University of Science and Technology
course_name: ريزپردازنده و زبان اسمبلي
course_description: Assembly
Microprocessors and Assembly language
3 واحد
مهندسي کامپيوتر
ريزپردازنده و زبان اسمبلي
اصلي کارشناسي
نام درس نام درس به انگليسي نوع واحد مقطع همنيازها پيشنيازها مطالب پيشنياز
معماري کامپيوتر￼￼￼￼￼￼￼￼￼￼￼￼ مفاهيم پايه در مدارهاي منطقي و معماري کامپيوتر
]0[ محمدمهدي همايونپور، فرزاد حصار، سيدامير اصغري، علي قنبري، ريزپردازنده و زبان اسمبلي، انتشارات￼￼￼￼ شي بهايي،0312.
[2] John Uffenbeck, The 8186/8188 Family: Design, Programming, and Interfacing, Prentice Hall, 3rd Edition, 2110.
[3] ATmega06 microcontroller datasheet.
[4] James L. Antonakos, The Pentium Microprocessor, Prentice-Hall, 0118.
[9] Holzner Steven Advanced Assembly Language, Prentice-Hall, 0119.
[6] Intel Corporation, Intel Pentium Developer’s Manual, Volume 3, 0119.
[7] NASM Development Team, NASM-Netwide Assembler User Manual, 2102.
[8] Richard H. Barnett, Sarah Cox, Larry O'Cull, Embedded C Programming and the
Atmel AVR, Delnmar Cengage Learning Publishing, 2100. [1] CodeVisionAVR C compiler, User manual, 2113.
[01] AVR Assembler, Atmel, 2114.
[00] Atmel Studio, Atmel.
[02] Winavr User Guide.
کتاب(هاي) مرجع و منابع￼￼￼ مفيد
اين درس دانش پايهاي ريزپردازنده و ميکروکنترلر را براي دانشجويان فراهم ميآورد، به گونهاي که آنها را قادر￼￼ به طراحي سيستمهاي مبتني بر ريزپردازنده و ميکروکنترلر خواهد ساخت. بخش قابل توجهي از اين درس بر ريزپردازنده 8186/88 بنا نهاده شده است. يادگيري اين ريزپردازنده، در عين سادگي ساختار نسبت به پردازندههاي بسيار پيشرفتهتر امروزي، اطلاعات پايهاي مهمي از مفاهيم طراحي ريزپردازنده را به دانشجويان
منتقل ميکند و آنها را براي يادگيري ساختارهاي پيچيدهتر آماده ميسازد. در عين حال در اين درس مباح مختصري از ريزپردازنده پيشرفتهتر پنتيوم مانند ثباتها، روشهاي آدرسدهي و مفاهيم عمليات حالت حقيقي و حفاظتشده براي نشان دادن مختصري از تفاوتهاي آن با ريزپردازنده 8186 (اختياري)، معرفي خواهد شد. بخشي ديگري از اين درس به معرفي ميکروکنترلرهاي خانواده AVR اختصاص يافته است تا بدين ترتيب دانشجويان با امکانات تعبيه شده در ميکروکنترلرها و مفاهيم مطرح در سيستمهاي نهفته شامل اجتماع انواع حافظهها، درگاههاي موازي قابل برنامهريزي، انواع وقفههاي سختافزاري و نرمافزاري و اولويت دهي آنها، زمانسنج/شمارنده براي استفاده در شمارش وقايع، زمانگيري و توليد سيگنالهاي از نوع PWM، مقايسهکننده آنالوگ، مبدل آنالوگ به ديجيتال و بعضي از انواع پروتکلهاي ارتباط سريال آشنا شوند. به منظور آشنايي با زبان اسمبلي، در اين درس ضمن آشنايي با مفاهيم اصلي زبان اسمبلي، دستورات اسمبلي ريزپردازنده 8186 و خانواده AVR مطرح گرديده و اسمبلرها و محيطهاي توسعه مجتمع )IDE( براي آنها
معرفي خواهند شد.
اهداف درس￼￼￼￼
دانشجوياني که اين درس را با موفقيت پشت سر بگذارند با مفاهيم بنيادي در طراحي و پيادهسازي￼
نتايج درس
57￼￼
سيستمهاي مبتني بر ريزپردازنده و ميکروکنترلر آشنا شده و بينش و توانايي مناسبي در موارد زير کسب￼￼ خواهند کرد:
0- توصيف معماري و سازمان يک ريزپردازنده 2- نوشتن برنامههاي اسمبلي با ساختار مناسب، با توضيحات کافي و قابل فهم 3- فهم روشهاي اتصال و زمانبندي انواع حافظههاي اصلي و ورودي/خروجيها به ريزپردازنده 4- فهم روشهاي دستدهي بين ريزپردازنده با ورودي/خروجيها 9- استفاده از اجزاء ميکروکنترلرها (زمانسنج/شمارنده، مبدل آنالوگ به ديجيتال، روشهاي مختلف
ارتباط سريال و ...) در کاربردهاي سيستمهاي نهفته 6- استفاده از محيطهاي توسعه مجتمع )IDE( به عنوان ابزارهاي نرمافزاري براي توسعه سيستمهاي
مبتني بر ريزپردازنده و ميکروکنترلر در کاربردهاي مختلف
0- مروري بر تاريخچه رايانهها و ريزپردازندهها، انواع ريزپردازندهها، انواع روشهاي بستهبندي￼￼￼￼￼￼ تراشههاي ريزپردازنده (اختياري)
2- مفاهيم پايه در سيستمهاي رايانهاي شامل: نمودار بلوکي يک ريزپردازنده و معرفي اجمالي اجزاء آن، واکشي و اجراي دستور، خطوط گذرگاه سهگانه (گذرگاه آدرس، داده و کنترل)، واحد پردازشگر مرکزي، حافظه و I/O، دستورالعملها، کدهاي عملياتي و عملوند و معرفي انواع چرخههاي گذرگاه
(bus cycles)
3- ساختار واحد پردازشگر مرکزي ريزپردازنده 8186/8188: ساختار واحد پردازشگر مرکزي 8186/88، واکشي و اجراي دستورالعمل، معرفي ثباتها، حافظه قسمتبندي شده، آدرسهاي فيزيکي و منطقي
4- معرفي اجمالي روشهاي آدرسدهي و دستورالعملهاي 8186/8188 9- آشنايي اجمالي با اجزاء و قابليتهاي ريزپردازنده پنتيوم، عمليات حالت حقيقي و حفاظت شده،
روشهاي آدرسدهي در پنتيوم (اختياري) 6- آشنايي با برنامهنويسي به زبان اسمبلي: معرفي شبهکدها، آموزش نصب و کار در محيط اسمبلر
NASM و نوشتن چند برنامه اسمبلي به زبان ريزپردازنده 8186/8188 7- طراحي واحد پردازشگر مرکزي 8186/8188 شامل: ساختار سيستمهاي سهگذرگاهه، زمانبندي
انواع سيکلهاي گذرگاه، معرفي پايههاي 8186/8188 در حالت کمينه، طراحي سختافزار پايه مبتني بر ريزپردازنده 8186/8188 شامل معرفي و توليد سيگنالهاي بازنشاني، پالس ساعت و Ready
8- حافظه در سيستمهاي مبتني بر ريزپردازنده: تعريف حافظه و مفاهيم پايهاي آن، طبقهبندي حافظهها، حافظه با دسترسي ترتيبي و تصادفي، حافظههاي ايستا، حافظههاي پويا، حافظههاي فقط خواندني، حافظههاي EPROM و EEPROM، حافظههاي خواندني-نوشتني، حافظه فللَش (اختياري)، تعيين پارامترهاي زمانبندي خواندن/نوشتن در حافظه درحالت کمينه ريزپردازنده
8186/8188، تهيه نقشه حافظه، چگونگي ارتباط SRAM و ROM با ريزپردازنده 8186/8188 و تکنيکهاي رمزگشايي کامل و جزئي آدرس براي دسترسي به حافظهها
1- روشهاي پايه ورودي/خروجي )I/O(: زمانبندي ارتباط ريزپردازنده با درگاههاي ورودي/خروجي I/O، طراحي درگاه ورودي و خروجي موازي، I/O نگاشته شده در حافظه، I/O برنامهريزي شده و روش سرکشي، I/O وقفهگرا، انواع وقفه، زمانبندي وقفه خارجي، اولويتدهي وقفهها، زمان
پاسخگويي به وقفه، بردار وقفه و روال سرويسدهي وقفه، معرفي اجمالي دسترسي مستقيم به حافظه (DMA) (اختياري)، طراحي کيبورد سطري و ماتريسي، طراحي مدار اتصال نمايش دهندههاي 7 قطعهاي، رله و LED به يک سيستم مبتني بر ريزپردازنده، معرفي اجمالي ارتباط
فهرست مباح￼￼￼
58￼
سريال همگام و ناهمگام.￼￼
01- معرفي اجمالي ميکروکنترلرها (مثل ميکروکنترلر ATMega16 از خانواده AVR يا يک
ميکروکنترلر از خانواده ARM يا هر ميکروکنترلر مناسب ديگر) شامل معرفي معماري و هسته مرکزي ميکروکنترلر شامل: معرفي پايهها، انواع منابع بازنشاني، انواع منابع ساعت، واکشي و اجراي دستورالعملها، حالتهاي آدرسدهي و معرفي اجمالي دستورالعملها، فضاي حافظه و انواع حافظه
داخلي، مجموعه ثباتها، ثبات وضعيت، تغذيه ميکروکنترلر، معرفي بيتهاي فيوز. 00- آشنايي با واحدهايهاي داخلي ميکروکنترلر: آشنايي با حالتهاي صرفهجويي در مصرف توان، وقفههاي داخلي و خارجي، زمانسنج/شمارنده، زمانسنج نگهبان، مقايسه کننده آنالوگ، مبدل آنالوگ به ديجيتال، معرفي اجمالي واسط ارتباط سريال USART، معرفي اجمالي واسطهاي سريال
SPI (اختياري) و TWI (اختياري)
02- معرفي اجمالي يک محيط IDE براي توسعه برنامه براي ميکروکنترلر و نوشتن برنامه به زبان
اسمبلي و يک زبان سطح بالا (مثل: Atmel Studio و CodeVision) (معرفي توسط استاد يا مطالعه توسط دانشجويان)
03- نکات مهم در طراحي سختافزار مدارات مبتني بر ريزپردازنده (اختياري) شامل مباح نويز و تاثير آن بر سيستمهاي ديجيتال، رعايت سطوح ولتاژ و جريان در اتصال قطعات از خانواده و تکنولوژيهاي مختلف، اثر انعکاس، اثر ظرفيت خازني در ورودي پايههاي تراشهها، تاخير انتشار،
دلايل استفاده از بافر و مانند آن (اختياري)
￼￼￼￼￼NASM Assembler, CodeVision, Atmel Studio, Winavr, Proteus
نرمافزارهاي مفيد تکاليف پيشنهادي 8 تکليف پروژههاي پيشنهادي 0 يا 2 پروژه
۳29￼￼￼￼￼￼ ۳01 ۳31 ۳39
تکاليف و 2 کوئيز پروژه امتحان ميانترم امتحان پايانترم
نمرهدهي پيشنهادي￼￼￼￼
￼￼[0] James L. Antonakos, The Intel Family of Microprocessors: Hardware and Software Principles and Applications, Thomson Delmar learning, 2116.X
[2] Barry B. Brey, Intel Microprocessors, Prentice Hall, 2118.
[3] Nilesh, B. Bahador, Microprocessors: 1216/1211, 12116/12216, 12316/12416 and the Pentium Family, PHI learning private Limited, 2212.
[4] Barry B. Brey, The Intel Microprocessors: 1216/1211, 12116/12111, 12216, 12316, 12416 - Pentium and Pentium Pro Processor - Architecture, Programming and Interfacing, Publisher, 1556.
[9] Walter A. Triebel, Avtar Singh, The 1211 and 1216 Microprocessors: Programming, Interfacing, Software, Hardware, and Applications, Publisher, year.
[6] Yu-Cheng Liu and Glenn A. Gibson, Microcomputer Systems: The 1216/1211
Family Architecture Programming and Design, 1516.
[7] Muhammad Ali Mazidi, Janice Mazidi, and Danny Causey, x86 PC: Assembly Language, Design, and Interfacing, Prentice Hall, 2111.
[8] A. S. Tanenbaum, A. S. Woodhull, Operating Systems design and implementation,
ساير مراجع￼￼￼
59￼
  Prentice-Hall, 0117.
  
course_semester: "Fall 2019"
description: |
    Instructor: Amir Mahdi Hosseini

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/course_template" # the subpath of your site, e.g. /blog/
url: "http://sauleh.github.io/course_template" # the base hostname & protocol for your site
syllabus: http://sauleh.github.io/course_template/syllabus/
githubdir: 

# Author/user information
email: instructor-first-name@iust.ac.ir
twitter_username: broken_twitter 
github_username:  broken_github
authorurl: "http://borken-url.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
