# Site settings
title: Iran University of Science and Technology
course_name: ريزپردازنده و زبان اسمبلي
course_description: Assembly
course_semester: "Fall 2019"
description: |
    Instructor: Amir Mahdi Hosseini

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/course_template" # the subpath of your site, e.g. /blog/
url: "http://sauleh.github.io/course_template" # the base hostname & protocol for your site
syllabus: http://sauleh.github.io/course_template/syllabus/
0 محمدمهدي همايونپور، فرزاد حصار، سيدامير اصغري، علي قنبري، ريزپردازنده و زبان اسمبلي، انتشارات￼￼￼￼ شي بهايي،0312.
2 "John Uffenbeck, The 8186/8188 Family :"" Design, Programming, and Interfacing, Prentice Hall, 3rd Edition, 2110.
3 ATmega06 microcontroller datasheet.
4 James L. Antonakos, The Pentium Microprocessor, Prentice-Hall, 0118.
9 Holzner Steven Advanced Assembly Language, Prentice-Hall, 0119.
6 Intel Corporation, Intel Pentium Developer’s Manual, Volume 3, 0119.
7 NASM Development Team, NASM-Netwide Assembler User Manual, 2102.
8 Richard H. Barnett, Sarah Cox, Larry O'Cull, Embedded C Programming and the
Atmel AVR, Delnmar Cengage Learning Publishing, 2100. [1] CodeVisionAVR C compiler, User manual, 2113.
01 AVR Assembler, Atmel, 2114.
00 Atmel Studio, Atmel.
02 Winavr User Guide.
githubdir: 

# Author/user information
email: instructor-first-name@iust.ac.ir
twitter_username: broken_twitter 
github_username:  broken_github
authorurl: "http://borken-url.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
